name: Make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: clang libbsd-dev libmodbus-dev libmosquitto-dev mosquitto-clients
    - name: make
      run: make
    - name: make lint
      run: make lint
    - name: make test
      run: make test
