name: Make

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #cc: [clang, gcc] # gcc build is broken for now
        cc: [clang]
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ${{ matrix.cc }} libbsd-dev libconfig-dev libmodbus-dev libmosquitto-dev
      - name: make with ${{ matrix.cc }}
        run: env CC=${{ matrix.cc }} make
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          path: growatt_exporter
          name: growatt_exporter

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang libbsd-dev libconfig-dev libmodbus-dev libmosquitto-dev mosquitto-clients
      - name: make lint
        run: env CC=clang make lint
      - name: make test
        run: env CC=clang make test
